export const STORAGE_KEYS = {
  CHAINS: 'momentum_chains',
  SCHEDULED_SESSIONS: 'momentum_scheduled_sessions',
  ACTIVE_SESSION: 'momentum_active_session',
  COMPLETION_HISTORY: 'momentum_completion_history',
  RSIP_NODES: 'momentum_rsip_nodes',
  RSIP_META: 'momentum_rsip_meta',
  RSIP_ATOMIC_JOURNAL: 'momentum_rsip_atomic_journal',
  RSIP_GROUPS: 'momentum_rsip_groups',
  RSIP_POLICY_LIBRARY: 'momentum_rsip_policy_library',
  RSIP_RUN_HISTORY: 'momentum_rsip_run_history',
  RSIP_TASK_LINKS: 'momentum_rsip_task_links',
  RSIP_EXECUTION_RECORDS: 'momentum_rsip_execution_records',
  TASK_TIME_STATS: 'momentum_task_time_stats',
  PET_STATE: 'momentum_pet_state',
  CHECKIN_STATE: 'momentum_checkin_state',
} as const;
